#!/usr/bin/python

import sys, os, subprocess, linecache
from termcolor import colored, cprint
import eix_pkg, cong

global file_name
global pkg_name
global sovp_count
global pkg_pver_inst
pkg_pver_inst = ''
pkg_name = sys.argv[1]
file_name = '/etc/portage/profile/package.provided'

def rec():
  pkg_full_name = eix_pkg.pfn(pkg_name)
  pkg_pver_inst = eix_pkg.pver_inst(pkg_name)
  pprov = open(file_name, 'a')
  pprov.write(pkg_full_name + '-9999\n')
  pprov.close
  print(colored(pkg_full_name.rstrip() + ' was frozen on version ' + pkg_pver_inst, 'green'))

def sovpad():
  sovp_isnt = cong.sovp(file_name, pkg_name)
  if sovp_isnt != 0:
    pkg_pver_inst = eix_pkg.pver_inst(pkg_name)
    print(colored('This package is already frozen on version ' + pkg_pver_inst, 'yellow'))
    sys.exit(1)

if len(sys.argv) == 1:
  print("Null argument", file=sys.stderr)
  sys.exit(1)
else:
  if os.path.isdir('/etc/portage/profile'):
    if os.path.isfile(file_name):
      sovpad()
      rec()
    else:
      print('List of freezed packages not found')
      open(file_name, 'w')
      print('List created', 'green')
      sovpad()
      rec()
  else:
    print('List of freezed packages not found')
    os.mkdir('/etc/portage/profile')
    open(file_name, 'w')
    print(colored('List created', 'green'))
    rec()
  
sys.exit(0)