#!/usr/bin/python

import sys, os
from termcolor import colored, cprint
import eix_pkg, cong

global file_name
global sovp_count
global pkg_pver_inst
global pkg_name
pkg_pver_inst = ''
arg_list = []
pkg_name = ''
file_name = '/etc/portage/profile/package.provided'

index = 1
while index != len(sys.argv):
  arg_list.append(sys.argv[index])
  index = index + 1

def rec(pkg_name):
  pprov = open(file_name, 'a')
  pkg_full_name = eix_pkg.pfn(pkg_name)
  pkg_pver_inst = eix_pkg.pver_inst(pkg_name)
  pprov.write(pkg_full_name + '-9999\n')
  print(colored(pkg_full_name.rstrip() + ' was frozen on version ' + pkg_pver_inst, 'green'))
  pprov.close

#def sovpad(pkg_name):
#  import cong
#  sovp_isnt = cong.sovp(file_name, pkg_name)
#  if sovp_isnt != 0:
#    pkg_full_name = eix_pkg.pfn(pkg_name)
#    pkg_pver_inst = eix_pkg.pver_inst(pkg_name)
#    print(colored(pkg_full_name.rstrip() + ' package is already frozen on version ' + pkg_pver_inst, 'yellow'))
#    return 1

        
def list_frz():
  #frz_list_raw = open('/tmp/frz_list_raw', 'w')
  frz_list_raw=[]
  with open(file_name, 'r') as pprov:
    pprov_line_raw = pprov.readline()
    while pprov_line_raw:
      pkg_name = pprov_line_raw[:-6]
      pkg_pver_inst = eix_pkg.pver_inst(pkg_name)
      frz_list_raw.append(pkg_name + '-' + pkg_pver_inst + '\n')
      pprov_line_raw = pprov.readline()
  #pprov.close
  #with open('/tmp/frz_list_raw', 'r') as frz_list_raw:
  print(colored('Frozen packages:', 'green'))
  print(''.join(sorted(frz_list_raw)), end='')
  #os.remove('/tmp/frz_list_raw')
          
if len(arg_list) == 0:
  print("Null argument", file=sys.stderr)
  sys.exit(1)
else:
  if os.path.isdir('/etc/portage/profile'):
    if os.path.isfile(file_name):
      if arg_list[0] == 'list':
        list_frz()
      else:
        index_list = 0
        while index_list != len(arg_list):
          pkg_name = arg_list[index_list]
          if cong.sovp(file_name, pkg_name) > 0:
            pkg_full_name = eix_pkg.pfn(pkg_name)
            pkg_pver_inst = eix_pkg.pver_inst(pkg_name)
            print(colored(pkg_full_name.rstrip() + ' package is already frozen on version ' + pkg_pver_inst, 'yellow'))
            index_list = index_list + 1
          else:
            rec(pkg_name)
            index_list = index_list + 1
    else:
      print('List of freezed packages not found')
      file_name_temp = open(file_name, 'w')
      print('List created', 'green')
      file_name_temp.close
      index_list = 0
      while index_list != len(arg_list):
        pkg_name = arg_list[index_list]
        rec(pkg_name)
        index_list = index_list + 1
  else:
    print('List of freezed packages not found')
    os.mkdir('/etc/portage/profile')
    file_name_temp = open(file_name, 'w')
    print(colored('List created', 'green'))
    file_name_temp.close
    index_list = 0
    while index_list != len(arg_list):
      pkg_name = arg_list[index_list]
      rec(pkg_name)
      index_list = index_list + 1
  
sys.exit(0)